title: Adithya Suresh # your name (or website title) here
logo: "Github Avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a final year undergrad from BITS Pilani K.K Birla Goa Campus looking to pursue a career in the data analytics field. I'm familiar with data analytics tools such as Excel, Python for data analysis, SQL, Power BI & Tableau.
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
